apiVersion: v1
kind: Service
metadata:
  name: app-http
  namespace: default
  labels:
    app: app-http
    version: v1
    component: api
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: app-http
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
