use anyhow::Result;
use colored::Colorize;
use std::fs;
use std::os::unix::fs::PermissionsExt;

pub fn run() -> Result<()> {
    let root = std::env::current_dir()?;
    let hooks_dir = root.join(".git").join("hooks");

    // Check if we're in a git repo
    if !root.join(".git").exists() {
        println!("{} .git directory not found. Are you in the repo root?", "✗".red());
        return Ok(());
    }

    // Create hooks directory if it doesn't exist
    if !hooks_dir.exists() {
        fs::create_dir_all(&hooks_dir)?;
    }

    // Pre-commit hook script
    let pre_commit_path = hooks_dir.join("pre-commit");
    let script = r#"#!/usr/bin/env bash
set -euo pipefail
# Rust-as-Spec Governance Pre-Commit Hook
# Generated by: cargo xtask install-hooks

echo "🔍 Running pre-commit governance checks..."

# Always use cargo run -p xtask to invoke the xtask crate
# The xtask binary itself has the Nix wrapper logic
cargo run -p xtask -- check
"#;

    fs::write(&pre_commit_path, script)?;

    // Make hook executable
    let mut perms = fs::metadata(&pre_commit_path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&pre_commit_path, perms)?;

    println!("{} Installed .git/hooks/pre-commit", "✓".green());
    println!("   The hook will run {} before each commit", "cargo run -p xtask -- check".cyan());
    println!("   (xtask handles Nix environment automatically)");

    Ok(())
}
