use anyhow::Result;
use colored::Colorize;
use std::fs;

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

pub fn run() -> Result<()> {
    let root = std::env::current_dir()?;
    let hooks_dir = root.join(".git").join("hooks");

    // Check if we're in a git repo
    if !root.join(".git").exists() {
        println!("{} .git directory not found. Are you in the repo root?", "✗".red());
        return Ok(());
    }

    // Create hooks directory if it doesn't exist
    if !hooks_dir.exists() {
        fs::create_dir_all(&hooks_dir)?;
    }

    // Pre-commit hook script
    let pre_commit_path = hooks_dir.join("pre-commit");

    // Use a single POSIX bash hook on all platforms
    // Git for Windows runs hooks via sh, so this works everywhere
    let low_res_export = if std::env::var_os("XTASK_LOW_RESOURCES").is_some() {
        "export XTASK_LOW_RESOURCES=1\n"
    } else {
        ""
    };

    let script = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
# Rust-as-Spec Governance Pre-Commit Hook
# Generated by: cargo xtask install-hooks

echo "🔍 Running pre-commit governance checks..."

{}# Always use cargo run -p xtask to invoke the xtask crate
# The xtask binary itself has the Nix wrapper logic
cargo run -p xtask -- check
"#,
        low_res_export
    );

    fs::write(&pre_commit_path, script)?;

    // Make hook executable (Unix only)
    #[cfg(unix)]
    {
        let mut perms = fs::metadata(&pre_commit_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&pre_commit_path, perms)?;
    }

    println!("{} Installed .git/hooks/pre-commit", "✓".green());
    println!("   The hook will run {} before each commit", "cargo run -p xtask -- check".cyan());
    println!("   (xtask handles Nix environment automatically)");

    Ok(())
}
