use crate::types::EndpointSchema;

/// Platform API Endpoints.
pub(crate) fn get_platform_endpoints() -> Vec<EndpointSchema> {
    vec![
        EndpointSchema {
            path: "/platform/status".to_string(),
            method: "GET".to_string(),
            description: "Get platform governance and service status".to_string(),
            request_type: None,
            response_type: "PlatformStatus".to_string(),
        },
        EndpointSchema {
            path: "/platform/graph".to_string(),
            method: "GET".to_string(),
            description: "Get full governance traceability graph".to_string(),
            request_type: None,
            response_type: "Graph".to_string(),
        },
        EndpointSchema {
            path: "/platform/schema".to_string(),
            method: "GET".to_string(),
            description: "Get platform schema definitions and API documentation".to_string(),
            request_type: None,
            response_type: "PlatformSchemas".to_string(),
        },
        EndpointSchema {
            path: "/platform/openapi".to_string(),
            method: "GET".to_string(),
            description: "Get OpenAPI specification (YAML)".to_string(),
            request_type: None,
            response_type: "text/yaml".to_string(),
        },
        EndpointSchema {
            path: "/platform/openapi.yaml".to_string(),
            method: "GET".to_string(),
            description: "Get OpenAPI specification (YAML)".to_string(),
            request_type: None,
            response_type: "text/yaml".to_string(),
        },
        EndpointSchema {
            path: "/platform/devex/flows".to_string(),
            method: "GET".to_string(),
            description: "Get developer experience flows and commands".to_string(),
            request_type: None,
            response_type: "DevExFlows".to_string(),
        },
        EndpointSchema {
            path: "/platform/docs/index".to_string(),
            method: "GET".to_string(),
            description: "Get documentation inventory".to_string(),
            request_type: None,
            response_type: "DocIndex".to_string(),
        },
        EndpointSchema {
            path: "/platform/tasks".to_string(),
            method: "GET".to_string(),
            description: "Get work items and tasks (filterable by status, REQ)".to_string(),
            request_type: None,
            response_type: "TasksResponse".to_string(),
        },
        EndpointSchema {
            path: "/platform/tasks/suggest-next".to_string(),
            method: "GET".to_string(),
            description: "Get suggested next steps for a task".to_string(),
            request_type: Some("query: task".to_string()),
            response_type: "SuggestedSequence".to_string(),
        },
        EndpointSchema {
            path: "/platform/agent/hints".to_string(),
            method: "GET".to_string(),
            description: "Get prioritized hints for tasks ready to work on".to_string(),
            request_type: Some("query: owner, label, requirement (optional)".to_string()),
            response_type: "AgentHintsResponse".to_string(),
        },
        EndpointSchema {
            path: "/platform/coverage".to_string(),
            method: "GET".to_string(),
            description: "Get AC coverage from BDD test results".to_string(),
            request_type: None,
            response_type: "CoverageResponse".to_string(),
        },
        EndpointSchema {
            path: "/platform/idp/snapshot".to_string(),
            method: "GET".to_string(),
            description: "Get IDP-ready governance snapshot for portal integration".to_string(),
            request_type: None,
            response_type: "IdpSnapshot".to_string(),
        },
        EndpointSchema {
            path: "/platform/questions".to_string(),
            method: "GET".to_string(),
            description: "Get design questions and ambiguities".to_string(),
            request_type: None,
            response_type: "QuestionsResponse".to_string(),
        },
        EndpointSchema {
            path: "/platform/friction".to_string(),
            method: "GET".to_string(),
            description: "Get development friction log entries".to_string(),
            request_type: None,
            response_type: "FrictionResponse".to_string(),
        },
        EndpointSchema {
            path: "/platform/forks".to_string(),
            method: "GET".to_string(),
            description: "Get registered fork information".to_string(),
            request_type: None,
            response_type: "ForksResponse".to_string(),
        },
        EndpointSchema {
            path: "/ui".to_string(),
            method: "GET".to_string(),
            description: "Platform dashboard UI".to_string(),
            request_type: None,
            response_type: "text/html".to_string(),
        },
        EndpointSchema {
            path: "/ui/graph".to_string(),
            method: "GET".to_string(),
            description: "Governance graph visualization UI".to_string(),
            request_type: None,
            response_type: "text/html".to_string(),
        },
        EndpointSchema {
            path: "/ui/flows".to_string(),
            method: "GET".to_string(),
            description: "DevEx flows visualization UI".to_string(),
            request_type: None,
            response_type: "text/html".to_string(),
        },
        EndpointSchema {
            path: "/ui/coverage".to_string(),
            method: "GET".to_string(),
            description: "AC coverage dashboard UI".to_string(),
            request_type: None,
            response_type: "text/html".to_string(),
        },
    ]
}
