name: DB
on: [pull_request]
jobs:
  atlas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -sSf https://atlasgo.sh | sh
      - run: atlas schema diff --to file://specs/db/atlas/schema.hcl
      - run: atlas migrate lint
