name: Docs
on:
  pull_request:
    paths: ['docs/**', 'backstage/**', '.github/workflows/ci-docs.yml']

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: pip install mkdocs
      - run: mkdocs build --strict -f backstage/mkdocs.yml
